# Describes the format for available Android TV and Fire TV services

adb_command:
  description: Send an ADB command to an Android TV / Fire TV device.
  fields:
    entity_id:
      description: Name(s) of Android TV / Fire TV entities.
      example: 'media_player.android_tv_living_room'
    command:
      description: Either a key command or an ADB shell command.
      example: 'HOME'
download:
  description: Download a file from your Android TV / Fire TV device to your Home Assistant instance.
  fields:
    entity_id:
      description: Name of Android TV / Fire TV entity.
      example: 'media_player.android_tv_living_room'
    device_path:
      description: The filepath on the Android TV / Fire TV device.
      example: '/storage/emulated/0/Download/example.txt'
    local_path:
      description: The filepath on your Home Assistant instance.
      example: '/config/example.txt'
upload:
  description: Upload a file from your Home Assistant instance to an Android TV / Fire TV device.
  fields:
    entity_id:
      description: Name(s) of Android TV / Fire TV entities.
      example: 'media_player.android_tv_living_room'
    device_path:
      description: The filepath on the Android TV / Fire TV device.
      example: '/storage/emulated/0/Download/example.txt'
    local_path:
      description: The filepath on your Home Assistant instance.
      example: '/config/example.txt'
