# Describes the format for available Android TV and Fire TV services

adb_command:
  description: Send an ADB command to an Android TV / Fire TV device.
  fields:
    entity_id:
      description: Name(s) of Android TV / Fire TV entities.
      example: 'media_player.android_tv_living_room'
    command:
      description: Either a key command or an ADB shell command.
      example: 'HOME'
adb_filesync:
  description: Transfer a file between your Home Assistant instance and an Android TV / Fire TV device.
  fields:
    entity_id:
      description: Name(s) of Android TV / Fire TV entities.
      example: 'media_player.android_tv_living_room'
    direction:
      description: Whether to push a file to the device or pull a file from the device; must be `push` or `pull`.
      example: 'push'
    device_path:
      description: The filepath on the Android TV / Fire TV device.
      example: '/home/example/path.txt'
    local_path:
      description: The filepath on your Home Assistant instance.
      example: '/config/example/path.txt'
